from discord.app_commands import Choice

text_model_choices = [
    Choice(name='📑 GPT-3.5-turbo', value='gpt-3.5-turbo'),
    Choice(name='📑 GPT-4', value='gpt-4'),
    Choice(name='👑 Claude-2.1', value='claude-2.1'),
    Choice(name='👑 Claude-3-haiku', value='claude-3-haiku'),
    Choice(name='🔮 Gemini-Pro', value='gemini-1.0-pro'),
    Choice(name='🐬 Dolphin Mixtral', value='dolphin-mixtral-8x7b'),
    Choice(name='🌌 Claude-3-Opus', value='claude-3-opus'),
    Choice(name='🇲 Mistral Large', value='mistral-large'),
    Choice(name='👍 GPT-4-Preview', value='gpt-4-0125-preview'),
    Choice(name='📰 Claude-Instant', value='claude-instant-1.2'),
    Choice(name='📭 OpenChat', value='openchat-3.5'),
    Choice(name='📰 Yi 34B', value='yi-34b-chat'),
    Choice(name='🔥 Yi 34B 200k', value='yi-34b-200k'),
    Choice(name='🦙 LLama 2 7B', value='llama2-7b'),
    Choice(name='🦙 LLama 2 13B', value='llama2-13b'),
    Choice(name='🦙 LLama 2 70B', value='llama2-70b'),
    Choice(name='😅 Gemma 2B', value='gemma-2b'),
    Choice(name='🇲 Mixtral Instruct', value='mixtral-8x7b-Instruct-v0.1'),
    Choice(name='😅 Gemma 7B', value='gemma-7b-it'),
    Choice(name='🦙 Code LLama 7B', value='code-llama-7b'),
    Choice(name='🦙 Code LLama 13B', value='code-llama-13b'),
    Choice(name='🦙 Code LLama 34B', value='code-llama-34b'),
    Choice(name='🇲 Mistral 7b', value='code-llama-13b'),
    Choice(name='🇲 Mistral lite', value='mistral-lite'),
    Choice(name='🇲 Mixtral 8x7b', value='mixtral-8x7b'),
    Choice(name='💵 GPT 4 OMNI ( This is too good to be true. )', value='gpt-4o')
]

image_model_choices = [
    Choice(name='🔮 DALL-E-2', value='dall-e-2'),
    Choice(name='🔮 DALL-E-3', value='dall-e-3'),
    Choice(name='🌅 Midjourney', value='midjourney'),
    Choice(name='🌅 Midjourney-5.1', value='midjourney-5.1'),
    Choice(name='🌅 Midjourney-5.2', value='midjourney-5.2'),
    Choice(name='🌅 Midjourney-6.0', value='midjourney-6.0'),
    Choice(name='🌅 NijiJourney-4', value='nijijourney-4'),
    Choice(name='🌅 NijiJourney-5', value='nijijourney-5'),
    Choice(name='👥 Absolutereality-v1.6', value='absolutereality-v1.6'),
    Choice(name='👥 Absolutereality-v1.8.1', value='absolutereality-v1.8.1'),
    Choice(name='🌌 Deliberate-v3', value='deliberate-v3'),
    Choice(name='🌌 Dreamshaper-v6', value='dreamshaper-v6'),
    Choice(name='🌌 Dreamshaper-v7', value='dreamshaper-v7'),
    Choice(name='🌌 Dreamshaper-v8', value='dreamshaper-v8'),
    Choice(name='🌌 Realistic-v4', value='realistic-v4'),
    Choice(name='🌅 Openjourney', value='openjourney'),
    Choice(name='🔥 Realisticvision-v1.4', value='realisticvision-v1.4'),
    Choice(name='🔥 Realisticvision-v4', value='realisticvision-v4'),
    Choice(name='🔥 Realisticvision-v5', value='realisticvision-v5'),
    Choice(name='🔥 Diffusionredshift-v10', value='diffusionredshift-v10'),
    Choice(name='🔥 Portrait', value='portrait'),
    Choice(name='🌅 Midchapter-v3', value='midchapter-v3'),
    Choice(name='🌅 ChildrensStories-v1', value='childrensstories-v1'),
    Choice(name='🌅 ChildrensStories-v2', value='childrensstories-v2'),
    Choice(name='🌅 Counterfeit-v3', value='counterfeit-v3'),
]
